
# Geometry =====================================================================
/CeBr3/GeometryFile CeBrA_2026.geo

/Chamber/Construct

/Brick/GeometryFile bricks.geo
/Brick/Construct

#/Mount/GeometryFile mounts.geo
#/Mount/Construct

# Processes ====================================================================
/Source/Simple 5000 keV

# Produce Auger electrons and X-rays
/process/em/auger true
/process/had/deex/readICdata true
/process/had/deex/setIC true

# Initialize run manager =======================================================
/run/initialize

/Output/Filename e5000.out
/Output/DetectorsOnly
/run/beamOn 10000000
