# Geometry =====================================================================
/Source/Capsule/Construct
/CeBr3/Type 3x4
/CeBr3/setZ 20 cm
/CeBr3/rotateX 90 deg

# Initialize run manager =======================================================
/run/initialize

# Initialize the source ========================================================
/gun/particle ion
/gun/ion 55 137

/Output/Filename cs137.out
/run/beamOn 1000000
